### ISSUE TITLE
Gunicorn crashes in production when clicking on a plotly graph

### ISSUE THREAD

**Issue by mboudet** [umr1085-irset/reproGenomicsViewer#39]
Clicking on the plotly graph trigger a request to get the group info.
Gunicorn workers timeout after 30s, but this request takes at least 90s.

Beyond the crash, the issue is that a simple click triggers a 90s request, without any information sent to the user.

1) Any way to shorten the computation?
2) Should we pre-process the table (when adding the study for instance?) so that the query would be a simple table fetch?
3) Or move the click event to a dedicated tab, with proper timeout management (rabbitmq job?)

**Comment by BioMAs** [comment]
Function removed for now

**Comment by BioMAs** [comment]
Function removed for now
